name: Converter curriculo.md para PDF e commitar na main

on:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: create file list
        id: files_list
        run: |
          echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/curriculo.pdf ${{ steps.files_list.outputs.files }}

      - name: Commit PDF and Push
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add output/curriculo.pdf
          git commit -m "Adicionar currículo em PDF"
          git push origin $GITHUB_REF
        continue-on-error: true
        shell: bash
