name: Converter md to PDF

on:
  push:
    branches:
      - main

jobs:
  generate-pdf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Create file List
        id: files_list
        run: |
          echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/curriculo.pdf ${{ steps.files_list.outputs.files }}

      - name: Commit PDF and Push
        run: |
          git config --local user.email "githubaction@example.com"
          git config --local user.name "GitHub Action"
          git add output/curriculo.pdf
          git commit -m "Adicionar currículo em PDF"
          git push origin $GITHUB_REF
        continue-on-error: true
        shell: bash

  tag-commit:
    needs: generate-pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
