name: Tagar versão em arquivos .md

on:
  push:
    paths:
      - '**.md'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar alterações
        id: check_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '.*\.md'; then
            echo "::set-output name=tag::true"
          else
            echo "::set-output name=tag::false"
          fi
      - name: Criar tag
        if: steps.check_changes.outputs.tag == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a v1.0 -m "Versão 1.0"
          git push origin v1.0
